version: '3.4'

services:
  samba:
    image: erriez/samba
    container_name: samba
    # build: .
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt:/mnt:z
      - /mnt2:/mnt2:z
    command: '-s "Mount;/mnt" -s "Erriez Volume;/mnt2;yes;no;no;erriez" -u "erriez;erriezpasswd" -p'
