name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# Global environment variables
env:
  PUSH_IMAGES: ${{ github.repository == 'erriez/docker-samba' && github.event_name != 'pull_request' }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      
      # Create image version from branch/tag
      - name: Create image version
        shell: bash
        run: |
          pinned_version="ci-build"
          if [ "$GITHUB_EVENT_NAME" != 'pull_request' ]; then
            if [ "$GITHUB_REF_NAME" == "master" ]; then
              pinned_version="latest"
            else
              pinned_version="${GITHUB_REF##*/}"
            fi
          fi
          echo "Building IMAGE_VERSION=$pinned_version"
          echo "IMAGE_VERSION=$pinned_version" >> $GITHUB_ENV

      # QEMU setup
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      # Setup buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # Login Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: env.PUSH_IMAGES == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and optional push
      - name: Build and optional push
        uses: docker/bake-action@v1.6.0
        with:
          files: build.hcl
          push: ${{ env.PUSH_IMAGES }}
