# https://github.com/jtagcat/action-docker-ghpackages/blob/main/.github/workflows/docker-ghcr.yml
name: Release to Github Packages. # https://ghcr.io

on: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
  push:
    branches:
      - main
  schedule:
    - cron: '36 4 */7 * *' # weekly builds

jobs:
  # Push image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Authenticate with ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push amd64
        run: |
          img="ghcr.io/${{ github.repository }}:amd64"
          docker build . --file Dockerfile --tag "${img}" --label "runnumber=${GITHUB_RUN_ID}"
          docker push "${img}"

      - name: Build and push aarch64
        run: |
          img="ghcr.io/${{ github.repository }}:aarch64"
          docker build . --file Dockerfile.aarch64 --tag "${img}" --label "runnumber=${GITHUB_RUN_ID}"
          docker push "${img}"

      - name: Build and push armhf
        run: |
          img="ghcr.io/${{ github.repository }}:armhf"
          docker build . --file Dockerfile.armhf --tag "${img}" --label "runnumber=${GITHUB_RUN_ID}"
          docker push "${img}"

