name: Build samba docker image
on:
  schedule:
    - cron: "36 4 */7 * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU for multi arch builds
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build images
        run: chmod u+x build.sh && export FROM_CI=true && ./build.sh

